# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZnSmrDQHTPWUEUXqw_V0rQpyNnG6zRno
"""

#eligble to vote or not
age=int(input("Enter your age="))
if age>=18:
  print("Eligible to vote")
else:
  print("not eligible to vote")