# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11RI9WpkkObabH6-HosX8NhqvzR_-R_77
"""

#prime number or not
i=int(input())
num=int(input())
if num>1:
 for i in range(2,num//2):
   if (num%2==0):
     print("not prime number")
     break
   else:
     print("prime")
else:
     print("not prime")