# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11RI9WpkkObabH6-HosX8NhqvzR_-R_77
"""

#positive or negative or Zero
a=int(input())
if a>=0:
  if a>0:
    print('positive no')
  else:
    print('Zero')  
else:
  print('negative number')

