# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kEsLOLSBK4plkxaZQfBzTV3dWHjAJL7P
"""

#quadratic equation
a=int(input())
b=int(input())
c=int(input())
d=b*b-4*a*c
if d>0:
  print("the roots are real,distinctand rational")
elif d==0:
  print("the roots are real,equal and rational")  
else:
  print("the roots are imaginary")