# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZnSmrDQHTPWUEUXqw_V0rQpyNnG6zRno
"""

#number is even or not
a=int(input())
if a%2==0:
  print("number is even")
else:
  print("number is odd")