# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11RI9WpkkObabH6-HosX8NhqvzR_-R_77
"""

#number positive or not
a=int(input())
if a>=0:
  print("number is positive")
else:
  print("numbe is negative")