# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CoxKlJLmWkjg_8wBJi2yonEcho7HshQ2
"""

#whether the charcter is vowel or consonant
ch=input("enter a character:")
if(ch=='A' or ch=='a' or ch=='e' or ch=='E' or ch=='i' or ch=='i' or ch=='I' or ch=='o' or ch=='O' or ch=='u' or ch=='U'):
  print("vowel")
else:
  print("consonant")